// / ///////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
// / ///////////////////////////////////////////////////////////////////////////////////////////

import { type SchemaType as $Schema } from './schema-lite';
import {
  type ModelResult as $ModelResult,
  type TypeDefResult as $TypeDefResult,
} from '@zenstackhq/orm';

export type Account = $ModelResult<$Schema, 'Account'>;
/**
 * Shape of the `auth()` function
 */
export type Auth = $TypeDefResult<$Schema, 'Auth'>;
export type Invitation = $ModelResult<$Schema, 'Invitation'>;
export type Member = $ModelResult<$Schema, 'Member'>;
export type Organization = $ModelResult<$Schema, 'Organization'>;
export type Session = $ModelResult<$Schema, 'Session'>;
export type Todo = $ModelResult<$Schema, 'Todo'>;
export type TodoList = $ModelResult<$Schema, 'TodoList'>;
export type User = $ModelResult<$Schema, 'User'>;
export type Verification = $ModelResult<$Schema, 'Verification'>;
